In [1]:
from IPython.display import HTML

# Youtube
display(HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/v-rIM2YvTfA?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>'))

C:\Users\iriska\Anaconda3\lib\site-packages\IPython\core\display.py:694: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")

In [3]:
import requests  
response = requests.get('https://www.cbr-xml-daily.ru/daily_json.js')

In [51]:
currencies = response.json()
currencies['Valute'].keys()

dict_keys(['AUD', 'AZN', 'GBP', 'AMD', 'BYN', 'BGN', 'BRL', 'HUF', 'HKD', 'DKK', 'USD', 'EUR', 'INR', 'KZT', 'CAD', 'KGS', 'CNY', 'MDL', 'NOK', 'PLN', 'RON', 'XDR', 'SGD', 'TJS', 'TRY', 'TMT', 'UZS', 'UAH', 'CZK', 'SEK', 'CHF', 'ZAR', 'KRW', 'JPY'])

In [22]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/dm-fedorov/pandas_basic/master/data/it_new.csv')

In [23]:
df.drop(['Дата рождения', 'Вакансия', 'Технология','Локация','З/п в валюте найма'], axis=1, inplace=True)

In [55]:
def get_course(x):
    if x == "RUB":
        return 1
    else:
        return currencies['Valute'][x]["Value"]

In [56]:
df["curenc_new"] = df["curenc"].replace({'zł': get_course('PLN'), '$': get_course('USD'), 'Kč': get_course('CZK'), 'Ft': get_course('HUF'), 'lev': get_course('AUD'), '₽': get_course('RUB'), '€': get_course('EUR')})
df.head(3)

   id       col curenc  curenc_new
0   1  140000.0      ₽         1.0
1   2  130000.0      ₽         1.0
2   3  200000.0      ₽         1.0

In [57]:
df['new val'] = df["col"] * df["curenc_new"]

In [58]:
df

    id        col curenc  curenc_new       new val
0    1  140000.00      ₽      1.0000  1.400000e+05
1    2  130000.00      ₽      1.0000  1.300000e+05
2    3  200000.00      ₽      1.0000  2.000000e+05
3    4  250000.00      ₽      1.0000  2.500000e+05
4    5  172413.00      ₽      1.0000  1.724130e+05
5    6  280000.00      ₽      1.0000  2.800000e+05
6    7  129000.00      ₽      1.0000  1.290000e+05
7    8  185000.00      ₽      1.0000  1.850000e+05
8    9  160000.00      ₽      1.0000  1.600000e+05
9   10    9500.00     zł     17.2617  1.639862e+05
10  11  170000.00      ₽      1.0000  1.700000e+05
11  12   12000.00     zł     17.2617  2.071404e+05
12  13   10500.00     zł     17.2617  1.812479e+05
13  14    9500.00     zł     17.2617  1.639862e+05
14  15  375000.00      ₽      1.0000  3.750000e+05
15  16  180000.00      ₽      1.0000  1.800000e+05
16  17   60000.00     Kč     28.5113  1.710678e+06
17  18  160000.00      ₽      1.0000  1.600000e+05
18  19  200000.00      ₽      1.0000  2.000000e+05
19  20  135000.00      ₽      1.0000  1.350000e+05
20  21  113000.00      ₽      1.0000  1.130000e+05
21  22    2000.00      $     71.5962  1.431924e+05
22  23  145000.00      ₽      1.0000  1.450000e+05
23  24  190000.00      ₽      1.0000  1.900000e+05
24  25  250000.00      ₽      1.0000  2.500000e+05
25  26  200000.00      ₽      1.0000  2.000000e+05
26  27  300000.00      ₽      1.0000  3.000000e+05
27  28  170000.00      ₽      1.0000  1.700000e+05
28  29  190000.00      ₽      1.0000  1.900000e+05
29  30  185000.00      ₽      1.0000  1.850000e+05
30  31  264367.82      ₽      1.0000  2.643678e+05
31  32    1800.00      $     71.5962  1.288732e+05
32  33  210000.00      ₽      1.0000  2.100000e+05
33  34  184000.00      ₽      1.0000  1.840000e+05
34  35  170000.00      ₽      1.0000  1.700000e+05
35  36  161000.00      ₽      1.0000  1.610000e+05
36  37  201149.43      ₽      1.0000  2.011494e+05
37  38   13000.00     zł     17.2617  2.244021e+05
38  39    6446.00    lev     46.7380  3.012731e+05
39  40  650000.00     Ft     22.2231  1.444502e+07
40  41  150000.00      ₽      1.0000  1.500000e+05
41  42  165000.00      ₽      1.0000  1.650000e+05
42  43  206896.00      ₽      1.0000  2.068960e+05
43  44  130631.00      ₽      1.0000  1.306310e+05
44  45  100000.00      ₽      1.0000  1.000000e+05
45  46  252900.00      ₽      1.0000  2.529000e+05
46  47    6000.00      $     71.5962  4.295772e+05
47  48  200000.00      ₽      1.0000  2.000000e+05
48  49  169540.23      ₽      1.0000  1.695402e+05
49  50  300000.00      ₽      1.0000  3.000000e+05
50  51  180000.00      ₽      1.0000  1.800000e+05
51  52  210000.00      ₽      1.0000  2.100000e+05
52  53  183908.00      ₽      1.0000  1.839080e+05
53  54  150000.00      ₽      1.0000  1.500000e+05
54  55   80000.00     Kč     28.5113  2.280904e+06
55  56    3212.00      €     77.8823  2.501579e+05
56  57    4000.00      €     77.8823  3.115292e+05
57  58    2980.00      €     77.8823  2.320893e+05